channels:
  - defaults
dependencies:
  - h5py=2.8.0
  - jupyterlab=1.2.4
  - matplotlib=3.1.1
  - nb_conda_kernels=2.2.2
  - numpy=1.17.4
  - opencv=3.4.2
  - pandas=0.25.3
  - pip=19.3.1
  - python=3.7.5
  - scipy=1.3.2
